#!/bin/bash

# 用法: ./parse_dump.sh FILE

# 参数错误时输出提示信息
if [ $# -ne 1 ]; then
        echo USAGE:
        echo ./parse_dump.sh FILE
        echo Here, FILE is generated by tcpdump via option -w
        exit
fi
# 用tcpdump解析指定文件，计算所有IP包的长度之和
sudo tcpdump -vvv -r $1 | awk -F '[ ()]' 'NR%2==1 {sum+=$20} END {print "Packets:", NR/2, "\nTotal traffic in byte:", sum}'

# Example
#sudo tcpdump -i wlp4s0 -vvv 'port 9999 and host 10.0.0.4' -w dump_nbftp_no_load_interval10_2min
#sudo tcpdump -i wlp4s0 -vvv 'port 9999 and host 10.0.0.4' -r dump_nbftp_no_load_interval10_2min | awk -F '[ ()]' 'NR%2==1 {sum+=$20} END {print "Packets:", NR/2, "\nTotal traffic in byte:", sum}'
